Repository traP-jp/traO-Judge-judge, pull requests merged in 2024-10, with the labels that each got.

#40 Feat/#39 add env dev
  .env.dev
  .gitignore
Labels: enhancement

#43 ✨ disable tasklist
  .github/pull_request_template.md
Labels: bug, documentation

#45 ⬆️ api version 1.0.1
  .env.dev
Labels: enhancement

#41 ✨ add sh for openapi generator
  judge-control-app/generate-api-crate.sh
Labels: enhancement

#47 ✨ generated openapi code
  judge-control-app/backend-api-schema/.gitignore
  judge-control-app/backend-api-schema/.openapi-generator-ignore
  judge-control-app/backend-api-schema/.openapi-generator/FILES
  judge-control-app/backend-api-schema/.openapi-generator/VERSION
  judge-control-app/backend-api-schema/.travis.yml
  judge-control-app/backend-api-schema/Cargo.toml
  judge-control-app/backend-api-schema/README.md
  judge-control-app/backend-api-schema/backend-api.yaml
  judge-control-app/backend-api-schema/docs/JudgeStatus.md
  judge-control-app/backend-api-schema/docs/SubmitResult.md
  judge-control-app/backend-api-schema/docs/SubmitResultApi.md
  judge-control-app/backend-api-schema/docs/TestResult.md
  judge-control-app/backend-api-schema/git_push.sh
  judge-control-app/backend-api-schema/src/apis/configuration.rs
  judge-control-app/backend-api-schema/src/apis/mod.rs
  judge-control-app/backend-api-schema/src/apis/submit_result_api.rs
  judge-control-app/backend-api-schema/src/lib.rs
  judge-control-app/backend-api-schema/src/models/judge_status.rs
  judge-control-app/backend-api-schema/src/models/mod.rs
  judge-control-app/backend-api-schema/src/models/submit_result.rs
  judge-control-app/backend-api-schema/src/models/test_result.rs
  judge-control-app/judge-api-server/.gitignore
  judge-control-app/judge-api-server/.openapi-generator-ignore
  judge-control-app/judge-api-server/.openapi-generator/FILES
  judge-control-app/judge-api-server/.openapi-generator/VERSION
  judge-control-app/judge-api-server/Cargo.toml
  judge-control-app/judge-api-server/README.md
  judge-control-app/judge-api-server/judge-api.yaml
  judge-control-app/judge-api-server/src/apis/judge.rs
  judge-control-app/judge-api-server/src/apis/mod.rs
  judge-control-app/judge-api-server/src/header.rs
  judge-control-app/judge-api-server/src/lib.rs
  judge-control-app/judge-api-server/src/models.rs
  judge-control-app/judge-api-server/src/server/mod.rs
  judge-control-app/judge-api-server/src/types.rs
Labels: enhancement

#51 add `&` to custom file trait
  judge-control-app/src/custom_file/traits.rs
Labels: bug

#57 Feat/#52 text resource repo trait
  judge-control-app/src/main.rs
  judge-control-app/src/text_resource_repository.rs
  judge-control-app/src/text_resource_repository/traits.rs
Labels: enhancement

#62 Feat/#61 remote exec
  judge-control-app/Cargo.toml
  judge-control-app/src/main.rs
  judge-control-app/src/remote_exec.rs
  judge-control-app/src/remote_exec/ssh.rs
  judge-control-app/src/remote_exec/ssh/tests.rs
  judge-control-app/src/remote_exec/traits.rs
  judge-control-app/src/telnet/traits.rs
  judge-control-app/tests/ssh_server/Dockerfile
Labels: enhancement

#66 add path for backend_api_schema and judge_api_server
  judge-control-app/Cargo.toml
  judge-control-app/backend-api-schema/src/apis/configuration.rs
  judge-control-app/backend-api-schema/src/apis/mod.rs
  judge-control-app/backend-api-schema/src/apis/submit_result_api.rs
  judge-control-app/backend-api-schema/src/lib.rs
  judge-control-app/backend-api-schema/src/models/judge_status.rs
  judge-control-app/backend-api-schema/src/models/submit_result.rs
  judge-control-app/backend-api-schema/src/models/test_result.rs
  judge-control-app/judge-api-server/src/apis/judge.rs
  judge-control-app/judge-api-server/src/apis/mod.rs
  judge-control-app/judge-api-server/src/header.rs
  judge-control-app/judge-api-server/src/lib.rs
  judge-control-app/judge-api-server/src/models.rs
  judge-control-app/judge-api-server/src/server/mod.rs
Labels: enhancement

#59 Feature/#7 add custom file
  judge-control-app/src/custom_file.rs
  judge-control-app/src/custom_file/directory.rs
  judge-control-app/src/custom_file/file_factory.rs
  judge-control-app/src/custom_file/text_file.rs
  judge-control-app/src/custom_file/traits.rs
Labels: enhancement

#68 judge recipeを実装
  judge-control-app/src/main.rs
  judge-control-app/src/models.rs
  judge-control-app/src/models/judge_recipe.rs
Labels: enhancement

#69 ✨ judge result
  judge-control-app/src/models.rs
  judge-control-app/src/models/judge_result.rs
Labels: enhancement
