Repository traP-jp/traO-Judge-judge, pull requests merged in 2024-09, with the labels that each got.

#11 クレートを作成
  judge-control-app/Cargo.toml
  judge-control-app/src/main.rs
  queue-app/Cargo.toml
  queue-app/src/main.rs
Labels: enhancement

#17 Feat/#16 file traits
  judge-control-app/src/custom_file.rs
  judge-control-app/src/custom_file/traits.rs
  judge-control-app/src/main.rs
Labels: enhancement

#24 Feat/#20 telnet trait
  judge-control-app/src/main.rs
  judge-control-app/src/telnet.rs
  judge-control-app/src/telnet/traits.rs
Labels: enhancement

#31 custom_fileのtraitを変更
  judge-control-app/src/custom_file/traits.rs
Labels: bug

#33 Feat/#32 lead labelcheck
  .github/workflows/label-checker.yml
Labels: enhancement, ci/test

#35 Issue #34: Use `create` instead of `get`
  judge-control-app/src/custom_file/traits.rs
Labels: enhancement
