Repository traP-jp/traO-Judge-judge, pull requests merged in 2025-05, with the labels that each got.

#365 Feat/#231 dep name repo
  lib/backend_infra/migrations/202504240141_add_dep_name.sql
  lib/backend_infra/src/model.rs
  lib/backend_infra/src/model/dep_name.rs
  lib/backend_infra/src/repository.rs
  lib/backend_infra/src/repository/dep_name.rs
  lib/judge_core/src/model/dep_name_repository.rs
  lib/judge_infra_mock/src/dep_name_repository.rs
  pylib/traopy_builder/src/builder.rs
Labels: enhancement

#388 exec-appでoutcomeをmountで受け渡しするように変更
  Cargo.lock
  app/exec_app/Cargo.toml
  app/exec_app/src/main.rs
  lib/jobapi/src/aws.rs
Labels: bug, infra

#369 Backend/#63 testcases
  Cargo.lock
  app/backend_app/Cargo.toml
  app/backend_app/src/di.rs
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/testcase.rs
  app/backend_app/src/model/problems.rs
  app/backend_app/src/model/testcase.rs
  lib/backend_domain/src/repository/procedure.rs
  lib/backend_infra/Cargo.toml
  lib/backend_infra/migrations/202504240141_add_dep_name.sql
  lib/backend_infra/src/provider.rs
  lib/backend_infra/src/repository/procedure.rs
  lib/backend_infra/src/repository/testcase.rs
  lib/backend_usecase/src/model/testcase.rs
  lib/backend_usecase/src/service/testcase.rs
  lib/judge_infra_mock/src/multi_proc_problem_registry/registry_server.rs
Labels: enhancement, backend
