Repository traP-jp/traO-Judge-judge, pull requests merged in 2025-04, with the labels that each got.

#260 Backend/fix/#64 get problem
  app/backend_app/src/di.rs
  app/backend_app/src/model.rs
  app/backend_app/src/model/problems.rs
  app/backend_app/src/model/testcase.rs
  lib/backend_domain/src/model/testcase.rs
  lib/backend_domain/src/repository/testcase.rs
  lib/backend_infra/src/model/testcase.rs
  lib/backend_infra/src/repository/testcase.rs
  lib/backend_usecase/src/model/problem.rs
  lib/backend_usecase/src/model/testcase.rs
  lib/backend_usecase/src/service/problem.rs
  lib/backend_usecase/src/service/testcase.rs
Labels: enhancement, backend

#269 Backend/fix/#79 todo
  app/backend_app/src/di.rs
  app/backend_app/src/handler/problems.rs
  app/backend_app/src/handler/users.rs
  app/backend_app/src/model/problems.rs
  app/backend_app/src/model/users.rs
  app/backend_app/tests/users/common/check.rs
  app/backend_app/tests/users/fixtures/common.sql
  lib/backend_domain/src/model/problem.rs
  lib/backend_infra/migrations/202504021427_remove_judgecode_path.sql
  lib/backend_infra/src/model/problem.rs
  lib/backend_infra/src/repository/problem.rs
  lib/backend_usecase/src/model/problem.rs
  lib/backend_usecase/src/model/user.rs
  lib/backend_usecase/src/service/problem.rs
  lib/backend_usecase/src/service/user.rs
Labels: enhancement, backend

#271 Release traopy util
  .github/workflows/traopy-util-release.yml
Labels: enhancement

#173 Feat/#171 implement actor
  lib/jobapi/Cargo.toml
  lib/jobapi/outcomes/.gitkeep
  lib/jobapi/src/actor.rs
  lib/jobapi/src/actor/file_factory.rs
  lib/jobapi/src/actor/handler.rs
  lib/jobapi/src/actor/instance.rs
  lib/jobapi/src/actor/instance_pool.rs
  lib/jobapi/src/actor/message.rs
  lib/jobapi/src/grpc.rs
  lib/jobapi/src/jobapi.rs
  lib/jobapi/src/lib.rs
Labels: enhancement, judge

#276 ✨ add judge control app for deployment
  app/judge_control_app/Cargo.toml
  app/judge_control_app/src/bin/main.rs
Labels: enhancement, judge

#279 Feat/#277 logging jobapi
  lib/jobapi/Cargo.toml
  lib/jobapi/src/actor/file_factory.rs
  lib/jobapi/src/actor/instance_pool.rs
  lib/jobapi/src/aws.rs
  lib/jobapi/src/jobapi.rs
Labels: enhancement, judge

#284 fix/#283 Correct S3 API usage
  lib/problem_registry/src/client.rs
Labels: bug, judge, infra

#286 🐛 fix url
  app/judge_control_app/src/bin/main.rs
Labels: bug

#289 create outcomes folder
  lib/jobapi/outcomes/.gitkeep
  lib/jobapi/src/actor/file_factory.rs
Labels: bug

#290 Fix/#287 cache build
  .github/workflows/build-judge-control-app.yml
Labels: enhancement, infra, build

#292 FileFactory has Uuid
  lib/jobapi/src/actor/file_factory.rs
  lib/jobapi/src/jobapi.rs
Labels: bug

#294 ignore ErrorKind::AlreadyExists
  lib/jobapi/src/actor/file_factory.rs
Labels: bug

#297 Backend/feat/#67 problem
  app/backend_app/src/di.rs
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/problems.rs
  lib/backend_domain/src/repository/problem.rs
  lib/backend_infra/src/repository/problem.rs
  lib/backend_usecase/src/service/problem.rs
Labels: enhancement, backend

#295 Backend/feat/#53 editorials
  .python-version
  app/backend_app/src/di.rs
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/editorial.rs
  app/backend_app/src/model.rs
  app/backend_app/src/model/editorials.rs
  app/backend_app/src/model/submissions.rs
  lib/backend_domain/src/model.rs
  lib/backend_domain/src/model/editorial.rs
  lib/backend_domain/src/model/problem.rs
  lib/backend_domain/src/model/procedure.rs
  lib/backend_domain/src/repository.rs
  lib/backend_domain/src/repository/editorial.rs
  lib/backend_domain/src/repository/procedure.rs
  lib/backend_infra/migrations/202504042220_fix_typo.sql
  lib/backend_infra/migrations/202504042223_add_is_public_column.sql
  lib/backend_infra/src/model.rs
  lib/backend_infra/src/model/editorial.rs
  lib/backend_infra/src/model/procedure.rs
  lib/backend_infra/src/provider.rs
  lib/backend_infra/src/repository.rs
  lib/backend_infra/src/repository/editorial.rs
  lib/backend_infra/src/repository/procedure.rs
  lib/backend_usecase/src/model.rs
  lib/backend_usecase/src/model/editorial.rs
  lib/backend_usecase/src/service.rs
  lib/backend_usecase/src/service/editorial.rs
  lib/backend_usecase/src/service/problem.rs
  lib/backend_usecase/src/service/testcase.rs
Labels: enhancement, backend

#304 reduce necessary envvar
  lib/jobapi/src/aws.rs
Labels: bug, infra

#310 #167 has cycle test
  lib/judge_core/Cargo.toml
  lib/judge_core/src/logic/has_cycle.rs
Labels: code quality

#312 Fix/#309 fix-s3-download
  lib/problem_registry/src/client.rs
Labels: bug, infra

#313 Fix #302 user_data.sh
  lib/jobapi/src/aws.rs
Labels: bug, judge, infra

#315 use subnet id from env
  lib/jobapi/src/aws.rs
Labels: enhancement, infra

#319 [workspace.dependencies] を使う
  Cargo.toml
  lib/jobapi/Cargo.toml
  lib/jobapi/src/aws.rs
  lib/jobapi/src/grpc.rs
Labels: refactor, judge

#317 Feat/#234 exec-app prebuild
  lib/jobapi/assets/user_data.sh
  lib/jobapi/src/aws.rs
Labels: enhancement, infra

#320 サーバ未起動時にリトライする
  Cargo.toml
  lib/jobapi/Cargo.toml
  lib/jobapi/src/grpc.rs
Labels: bug, judge

#323 rename exec-http-server to exec-app
  lib/jobapi/assets/user_data.sh
Labels: bug, infra

#328 gRPC のレスポンス受け取り時の処理が間違っている
  lib/jobapi/src/grpc.rs
Labels: bug, judge

#329 Feat/#324 pull image from ecr
  .github/workflows/build-exec-app.yml
  app/exec_app/src/main.rs
  lib/jobapi/assets/user_data.sh
Labels: bug, infra

#331 increase ebs size to 32 GiB (from 8)
  lib/jobapi/src/aws.rs
Labels: bug, infra

#332 fix InvalidBlockDeviceMapping error
  lib/jobapi/src/aws.rs
Labels: bug, infra

#336 インスタンス起動待ち時間延ばす
  lib/jobapi/src/grpc.rs
Labels: bug, judge

#334 split cache
  .github/workflows/build-exec-app.yml
  .github/workflows/build-judge-control-app.yml
Labels: bug, judge, infra

#342 📈 tracing for runner
  lib/judge_core/Cargo.toml
  lib/judge_core/src/logic/runner.rs
Labels: enhancement, code quality

#343 fix build error caused by #340
  lib/jobapi/src/aws.rs
Labels: bug, infra

#346 mkdir and add log
  app/exec_app/Cargo.toml
  app/exec_app/src/main.rs
Labels: bug, infra

#344 change cache name
  .github/workflows/_test-judge-control-app-release.yml
  .github/workflows/_test-judge-control-app.yml
  .github/workflows/backend-with-external.yml
  .gitignore
  Cargo.lock
Labels: bug, code quality, judge

#347 ✨ add v0 wrapper for procedure builder
  lib/judge_core/src/logic/problem_presets/normal_judge.rs
  lib/judge_core/src/logic/problem_presets/normal_judge_build.py
  lib/judge_core/src/logic/problem_presets/normal_judge_run.py
  lib/judge_core/src/logic/problem_presets/normal_judge_summarize.py
Labels: enhancement, judge, backend

#352 Backend/#89 neoshowcase
  Cargo.toml
  app/backend_app/Cargo.toml
  app/backend_app/DockerFile
  app/backend_app/docker-compose.yaml
  app/backend_app/src/lib.rs
  lib/backend_domain/Cargo.toml
  lib/backend_domain/src/external.rs
  lib/backend_domain/src/external/object_strage.rs
  lib/backend_infra/Cargo.toml
  lib/backend_infra/src/external.rs
  lib/backend_infra/src/external/object_strage.rs
  lib/backend_infra/src/provider.rs
Labels: enhancement, backend

#349 Fix/#348 exec-app outcome path
  Cargo.lock
  app/exec_app/src/main.rs
Labels: bug, infra

#360 create output_parser.rs
  lib/judge_core/src/logic.rs
  lib/judge_core/src/logic/output_parser.rs
  lib/judge_core/src/logic/runner.rs
  lib/judge_core/src/model/judge_output.rs
Labels: refactor, judge

#366 Backend/#35 icon
  Cargo.lock
  Cargo.toml
  app/backend_app/.env.dev
  app/backend_app/src/di.rs
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/icon.rs
  app/backend_app/src/handler/users.rs
  lib/backend_domain/src/model.rs
  lib/backend_domain/src/model/icon.rs
  lib/backend_domain/src/model/rules.rs
  lib/backend_domain/src/repository.rs
  lib/backend_domain/src/repository/icon.rs
  lib/backend_infra/migrations/202504301511_add-icon-table.sql
  lib/backend_infra/src/model.rs
  lib/backend_infra/src/model/icon.rs
  lib/backend_infra/src/provider.rs
  lib/backend_infra/src/repository.rs
  lib/backend_infra/src/repository/icon.rs
  lib/backend_usecase/Cargo.toml
  lib/backend_usecase/src/model/user.rs
  lib/backend_usecase/src/service.rs
  lib/backend_usecase/src/service/icon.rs
  lib/backend_usecase/src/service/user.rs
Labels: enhancement, backend
