Repository traP-jp/traO-Judge-judge, pull requests merged in 2025-03, with the labels that each got.

#166 Add func Has_Cycle
  lib/judge_core/src/has_cycle.rs
  lib/judge_core/src/lib.rs
Labels: enhancement

#168 Feat/#159 define messages between actors
  lib/jobapi/Cargo.toml
  lib/jobapi/src/actor.rs
  lib/jobapi/src/actor/handler.rs
  lib/jobapi/src/actor/message.rs
  lib/jobapi/src/lib.rs
Labels: enhancement

#170 Feat/#169 define aws client type
  lib/jobapi/Cargo.toml
  lib/jobapi/src/aws.rs
  lib/jobapi/src/lib.rs
Labels: enhancement

#165 Backend/feat/#60 post problems
  app/backend_app/src/di.rs
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/problems.rs
  app/backend_app/src/model.rs
  app/backend_app/src/model/problems.rs
  app/backend_app/tests/users/fixtures/common.sql
  lib/backend_domain/src/model/problem.rs
  lib/backend_domain/src/repository/problem.rs
  lib/backend_infra/migrations/202502242153_create-table.sql
  lib/backend_infra/migrations/202503051859_update-nortmal_problems.sql
  lib/backend_infra/src/model/problem.rs
  lib/backend_infra/src/repository/problem.rs
  lib/backend_usecase/src/model.rs
  lib/backend_usecase/src/model/problem.rs
  lib/backend_usecase/src/service.rs
  lib/backend_usecase/src/service/problem.rs
Labels: enhancement

#178 🎨 improve heavy nest of judge_output enums
  lib/judge_core/src/judge_output.rs
  lib/judge_core/src/runner.rs
Labels: refactor

#176 🎨 replace impl Future<... to async_trait
  lib/jobapi/Cargo.toml
  lib/jobapi/src/jobapi.rs
  lib/judge_core/Cargo.toml
  lib/judge_core/src/job.rs
  lib/judge_core/src/problem_registry.rs
  lib/local_jobapi/Cargo.toml
  lib/local_jobapi/src/jobapi.rs
  lib/local_problem_registry/Cargo.toml
  lib/local_problem_registry/src/registry_client.rs
  lib/local_problem_registry/src/registry_server.rs
  lib/problem_registry/Cargo.toml
  lib/problem_registry/src/client.rs
  lib/problem_registry/src/server.rs
Labels: refactor

#183 🚚 refactor judge_core structure
  lib/jobapi/src/actor/handler.rs
  lib/jobapi/src/actor/message.rs
  lib/jobapi/src/aws.rs
  lib/jobapi/src/jobapi.rs
  lib/judge_core/src/lib.rs
  lib/judge_core/src/logic.rs
  lib/judge_core/src/logic/has_cycle.rs
  lib/judge_core/src/logic/procedure_builder.rs
  lib/judge_core/src/logic/registered_procedure_converter.rs
  lib/judge_core/src/logic/runner.rs
  lib/judge_core/src/logic/writer_schema_transpiler.rs
  lib/judge_core/src/model.rs
  lib/judge_core/src/model/identifiers.rs
  lib/judge_core/src/model/job.rs
  lib/judge_core/src/model/judge_output.rs
  lib/judge_core/src/model/problem_registry.rs
  lib/judge_core/src/model/procedure.rs
  lib/judge_core/src/model/procedure/registered.rs
  lib/judge_core/src/model/procedure/runtime.rs
  lib/judge_core/src/model/procedure/writer_schema.rs
  lib/local_jobapi/src/jobapi.rs
  lib/local_problem_registry/src/registry_client.rs
  lib/local_problem_registry/src/registry_server.rs
  lib/problem_registry/src/client.rs
  lib/problem_registry/src/server.rs
  pylib/traopy/src/local_judge.rs
  pylib/traopy/src/models/dependency.rs
  pylib/traopy/src/models/empty_directory.rs
  pylib/traopy/src/models/execution.rs
  pylib/traopy/src/models/resource_kind.rs
  pylib/traopy/src/models/runtime_text.rs
  pylib/traopy/src/models/text.rs
  pylib/traopy/src/procedure_builder.rs
Labels: refactor

#185 ✨ id and uuid conversion
  lib/judge_core/src/model/identifiers.rs
Labels: enhancement

#193 ✨ judge api trait
  lib/judge_core/src/model.rs
  lib/judge_core/src/model/judge.rs
Labels: enhancement, judge

#196 Feat/#194 judge api impl
  lib/judge_core/src/logic.rs
  lib/judge_core/src/logic/judge_api_impl.rs
  lib/judge_core/src/logic/runner.rs
  lib/judge_core/src/model/job.rs
  lib/judge_core/src/model/judge.rs
  lib/judge_core/src/model/problem_registry.rs
  lib/local_problem_registry/src/registry_server.rs
Labels: enhancement, judge

#195 Feat/#163 grpc v1
  Cargo.toml
  lib/back_judge_grpc/Cargo.toml
  lib/back_judge_grpc/proto/common.proto
  lib/back_judge_grpc/proto/judge.proto
  lib/back_judge_grpc/proto/judge_request.proto
  lib/back_judge_grpc/proto/judge_response.proto
  lib/back_judge_grpc/src/bin/gen.rs
  lib/back_judge_grpc/src/client.rs
  lib/back_judge_grpc/src/generated.rs
  lib/back_judge_grpc/src/generated/_.rs
  lib/back_judge_grpc/src/lib.rs
  lib/back_judge_grpc/src/server.rs
  lib/grpc_schema/Cargo.toml
  lib/grpc_schema/build.rs
  lib/grpc_schema/src/lib.rs
  lib/judge_core/Cargo.toml
  lib/judge_core/src/logic/judge_api_impl.rs
  lib/judge_core/src/logic/procedure_builder.rs
  lib/judge_core/src/logic/registered_procedure_converter.rs
  lib/judge_core/src/logic/runner.rs
  lib/judge_core/src/logic/writer_schema_transpiler.rs
  lib/judge_core/src/model/job.rs
  lib/judge_core/src/model/judge.rs
  lib/judge_core/src/model/problem_registry.rs
  lib/judge_core/src/model/procedure/registered.rs
  lib/judge_core/src/model/procedure/runtime.rs
  lib/judge_core/src/model/procedure/writer_schema.rs
  pylib/traopy/example/problems/addition/judge_procedure_sample.json
  pylib/traopy/python/traopy/lowlevel.pyi
  pylib/traopy/src/models/execution.rs
  pylib/traopy/src/models/output.rs
  pylib/traopy/src/procedure_builder.rs
Labels: enhancement, judge

#174 Backend/feat/#80
  Cargo.toml
  lib/backend_domain/Cargo.toml
  lib/backend_domain/src/external/mail.rs
  lib/backend_domain/src/external/object_strage.rs
  lib/backend_domain/src/repository/auth.rs
  lib/backend_domain/src/repository/problem.rs
  lib/backend_domain/src/repository/session.rs
  lib/backend_domain/src/repository/submission.rs
  lib/backend_domain/src/repository/user.rs
  lib/backend_usecase/Cargo.toml
  lib/backend_usecase/src/service/auth.rs
Labels: ci/test

#201 Feat/#200 multi proc problem registry
  lib/local_problem_registry/Cargo.toml
  lib/local_problem_registry/src/lib.rs
  lib/local_problem_registry/src/multi_proc.rs
  lib/local_problem_registry/src/multi_proc/registry_client.rs
  lib/local_problem_registry/src/multi_proc/registry_server.rs
  lib/local_problem_registry/src/one_proc.rs
  lib/local_problem_registry/src/one_proc/registry_client.rs
  lib/local_problem_registry/src/one_proc/registry_server.rs
  pylib/traopy/src/local_judge.rs
Labels: enhancement, ci/test, judge

#204 Feat/#203 judge ctrl mock
  .dockerignore
  app/judge_control_app/Cargo.toml
  app/judge_control_app/mock.Dockerfile
  app/judge_control_app/src/bin/main.rs
  app/judge_control_app/src/bin/mock.rs
  lib/back_judge_grpc/src/lib.rs
  lib/back_judge_grpc/src/server.rs
  lib/judge_core/src/logic/judge_api_impl.rs
  lib/local_problem_registry/src/multi_proc/registry_client.rs
  lib/local_problem_registry/src/multi_proc/registry_server.rs
Labels: enhancement, ci/test, judge

#208 Refactor/#207 traopy localjudge must use judge api
  pylib/traopy/src/local_judge.rs
Labels: refactor, rust-python-integration

#212 🎉 traopy_util
  Cargo.toml
  pylib/traopy_util/.gitignore
  pylib/traopy_util/.python-version
  pylib/traopy_util/Cargo.toml
  pylib/traopy_util/README.md
  pylib/traopy_util/pyproject.toml
  pylib/traopy_util/python/traopy_util.pyi
  pylib/traopy_util/src/bin/gen_stub.rs
  pylib/traopy_util/src/lib.rs
  pylib/traopy_util/src/v0.rs
  pylib/traopy_util/src/v0/output.rs
  pyproject.toml
  requirements-dev.lock
  requirements.lock
Labels: enhancement, judge, rust-python-integration

#216 Feat/#215 traopy util metadata reader
  lib/judge_core/src/constant.rs
  lib/judge_core/src/lib.rs
  pylib/traopy_util/python/traopy_util.pyi
  pylib/traopy_util/src/v0.rs
  pylib/traopy_util/src/v0/input.rs
Labels: enhancement, judge, rust-python-integration

#218 ✨ normal judge preset(todo)
  lib/judge_core/src/logic.rs
  lib/judge_core/src/logic/problem_presets.rs
  lib/judge_core/src/logic/problem_presets/normal_judge.rs
Labels: enhancement, judge, backend

#220 🎨 refactor judge mock all
  Cargo.toml
  app/judge_control_app/Cargo.toml
  app/judge_control_app/src/bin/mock.rs
  lib/judge_core/src/logic.rs
  lib/judge_core/src/logic/writer_schema_registerer.rs
  lib/judge_core/src/model.rs
  lib/judge_core/src/model/dep_name_repository.rs
  lib/judge_core/src/model/problem_registry.rs
  lib/judge_infra_mock/Cargo.toml
  lib/judge_infra_mock/src/dep_name_repository.rs
  lib/judge_infra_mock/src/jobapi.rs
  lib/judge_infra_mock/src/jobapi/jobapi.rs
  lib/judge_infra_mock/src/jobapi/tokens.rs
  lib/judge_infra_mock/src/lib.rs
  lib/judge_infra_mock/src/multi_proc_problem_registry.rs
  lib/judge_infra_mock/src/multi_proc_problem_registry/registry_client.rs
  lib/judge_infra_mock/src/multi_proc_problem_registry/registry_server.rs
  lib/judge_infra_mock/src/one_proc_problem_registry.rs
  lib/judge_infra_mock/src/one_proc_problem_registry/registry_client.rs
  lib/judge_infra_mock/src/one_proc_problem_registry/registry_server.rs
  lib/local_problem_registry/Cargo.toml
  lib/local_problem_registry/src/lib.rs
  lib/problem_registry/src/server.rs
  pylib/traopy_builder/Cargo.toml
  pylib/traopy_builder/src/local_judge.rs
Labels: enhancement, refactor, judge

#221 🎨 use same edition and version project-wide
  Cargo.toml
  app/backend_app/Cargo.toml
  app/judge_control_app/Cargo.toml
  lib/back_judge_grpc/Cargo.toml
  lib/backend_domain/Cargo.toml
  lib/backend_infra/Cargo.toml
  lib/backend_usecase/Cargo.toml
  lib/jobapi/Cargo.toml
  lib/judge_core/Cargo.toml
  lib/judge_infra_mock/Cargo.toml
  lib/problem_registry/Cargo.toml
  pylib/traopy_builder/Cargo.toml
  pylib/traopy_util/Cargo.toml
Labels: refactor, build

#223 ✨ compile run in traopy_util
  lib/judge_core/src/constant.rs
  pylib/traopy_util/src/v0.rs
  pylib/traopy_util/src/v0/command.rs
Labels: enhancement, rust-python-integration

#224 ✨ judge merge utility
  pylib/traopy_util/src/v0.rs
  pylib/traopy_util/src/v0/judge_status.rs
  pylib/traopy_util/src/v0/output.rs
Labels: enhancement, rust-python-integration

#202 Feat/#139 AWS
  lib/jobapi/Cargo.toml
  lib/jobapi/assets/user_data.sh
  lib/jobapi/src/aws.rs
Labels: enhancement, infra

#228 Feat/#227 remove unnecessary function
  lib/jobapi/src/aws.rs
Labels: enhancement

#233 add normal judge testcase name and limits
  Cargo.toml
  lib/judge_core/src/logic/problem_presets/normal_judge.rs
Labels: enhancement

#197 backend/feat/#62-get-problems
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/problems.rs
  app/backend_app/src/model/problems.rs
  lib/backend_domain/src/model/problem.rs
  lib/backend_domain/src/repository/problem.rs
  lib/backend_infra/src/repository/problem.rs
  lib/backend_usecase/src/model/problem.rs
  lib/backend_usecase/src/service/problem.rs
Labels: enhancement, backend

#238 🐛 time allocation for exec-job must be specified in procedure
  lib/back_judge_grpc/proto/judge_request.proto
  lib/back_judge_grpc/src/generated.rs
  lib/back_judge_grpc/src/generated/_.rs
  lib/judge_core/src/logic/registered_procedure_converter.rs
  lib/judge_core/src/logic/writer_schema_registerer.rs
  lib/judge_core/src/model/procedure/registered.rs
  lib/judge_core/src/model/procedure/runtime.rs
  lib/judge_core/src/model/procedure/writer_schema.rs
  pylib/traopy_builder/src/models/execution.rs
  pylib/traopy_builder/src/procedure_builder.rs
Labels: bug, enhancement, judge

#230 Feat/#229-decide-proto
  Cargo.toml
  lib/judge_exec_grpc/Cargo.toml
  lib/judge_exec_grpc/proto/execute.proto
  lib/judge_exec_grpc/src/bin/gen.rs
  lib/judge_exec_grpc/src/generated/_.rs
Labels: enhancement

#242 🔥 delete depId related features of problem registry
  lib/judge_core/src/logic/writer_schema_registerer.rs
  lib/judge_core/src/model/problem_registry.rs
  lib/judge_infra_mock/src/multi_proc_problem_registry/registry_server.rs
  lib/judge_infra_mock/src/one_proc_problem_registry.rs
  lib/judge_infra_mock/src/one_proc_problem_registry/registry_server.rs
  lib/problem_registry/src/server.rs
  pylib/traopy_builder/src/local_judge.rs
Labels: bug, refactor, judge

#246 ✨ add wrapper of testcase removal
  lib/judge_core/src/logic.rs
  lib/judge_core/src/logic/registered_procedure_remover.rs
Labels: enhancement, judge

#247 Backend/feat/#59 testcases
  Cargo.toml
  lib/backend_domain/src/model.rs
  lib/backend_domain/src/model/precedure.rs
  lib/backend_domain/src/model/testcase.rs
  lib/backend_domain/src/repository.rs
  lib/backend_domain/src/repository/precedure.rs
  lib/backend_domain/src/repository/testcase.rs
  lib/backend_infra/migrations/202503210418_remove_testcase_path.sql
  lib/backend_infra/migrations/202503212236_add_procedure_table.sql
  lib/backend_infra/src/model.rs
  lib/backend_infra/src/model/procedure.rs
  lib/backend_infra/src/model/testcase.rs
  lib/backend_infra/src/provider.rs
  lib/backend_infra/src/repository.rs
  lib/backend_infra/src/repository/procedure.rs
  lib/backend_infra/src/repository/testcase.rs
  lib/backend_usecase/Cargo.toml
  lib/backend_usecase/src/model.rs
  lib/backend_usecase/src/model/testcase.rs
  lib/backend_usecase/src/service.rs
  lib/backend_usecase/src/service/testcase.rs
Labels: enhancement, backend

#251 Refactor/#250 local judge
  .gitignore
  lib/judge_core/src/constant/env_var_exec.rs
  lib/judge_core/src/logic/runner.rs
  lib/judge_core/src/logic/writer_schema_registerer.rs
  lib/judge_core/src/model/judge_output.rs
  lib/judge_infra_mock/src/jobapi/jobapi.rs
  pylib/example/.env.dev
  pylib/example/languages.json
  pylib/example/problems/addition/builder.ipynb
  pylib/example/problems/addition/scripts/build.py
  pylib/example/problems/addition/scripts/run.py
  pylib/example/problems/addition/scripts/summarize.py
  pylib/example/pyproject.toml
  pylib/traopy_builder/python/traopy_builder/builder/__init__.pyi
  pylib/traopy_builder/src/builder.rs
  pylib/traopy_util/python/traopy_util/util/v0.pyi
  pylib/traopy_util/src/common.rs
  pylib/traopy_util/src/lib.rs
  pylib/traopy_util/src/v0.rs
  pylib/traopy_util/src/v0/command.rs
  pylib/traopy_util/src/v0/constant.rs
  pylib/traopy_util/src/v0/exec_with_stats.rs
  requirements-dev.lock
  requirements.lock
Labels: enhancement

#253 Feat/#252 traopy visualize
  .github/workflows/python.yml
  pylib/example/problems/addition/builder.ipynb
  pylib/example/pyproject.toml
  pylib/traopy_visualize/pyproject.toml
  pylib/traopy_visualize/src/traopy_visualize/__init__.py
  pylib/traopy_visualize/src/traopy_visualize/_parser.py
  pylib/traopy_visualize/src/traopy_visualize/_visualize.py
  pyproject.toml
  requirements-dev.lock
  requirements.lock
Labels: enhancement, rust-python-integration

#259 backend GET/submissions
  app/backend_app/src/handler.rs
  app/backend_app/src/handler/submissions.rs
  app/backend_app/src/model/submissions.rs
  lib/backend_domain/src/model.rs
  lib/backend_domain/src/model/submission.rs
  lib/backend_domain/src/model/submisson.rs
  lib/backend_domain/src/repository/submission.rs
  lib/backend_infra/src/model/submission.rs
  lib/backend_infra/src/repository/submission.rs
  lib/backend_usecase/src/model/submission.rs
  lib/backend_usecase/src/service/submission.rs
Labels: enhancement, backend

#262 maxrss is in byte in macos
  pylib/traopy_util/src/v0/exec_with_stats.rs
Labels: bug
